CREATE DATABASE shop_db;
GRANT ALL PRIVILEGES ON shop_db.* TO 'shop_db_user'@'%' IDENTIFIED BY 'shop_db_pass';
USE shop_db;

CREATE TABLE PEDIDO (
            ID VARCHAR(36) NOT NULL,
			USER VARCHAR(255) NOT NULL,
            EMAIL VARCHAR(255) NOT NULL,
            STATE VARCHAR(255) NOT NULL,
			PRIMARY KEY (ID)
)ENGINE INNODB;

CREATE TABLE PRODUCTO (
			ID INTEGER NOT NULL AUTO_INCREMENT,
			NAME VARCHAR(255) NOT NULL,
			PRIMARY KEY (ID)
)ENGINE INNODB;

CREATE TABLE PRODUCTO_PEDIDO (
			ID INTEGER NOT NULL AUTO_INCREMENT,
			PEDIDO VARCHAR(36) NOT NULL,
            PRODUCTO INTEGER NOT NULL,
            CANTIDAD INTEGER NOT NULL,
			PRIMARY KEY (ID),
            FOREIGN KEY (PEDIDO) REFERENCES PEDIDO (ID) ON DELETE CASCADE,
            FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO (ID) ON DELETE CASCADE 
)ENGINE INNODB;

CREATE TABLE USUARIO (
			ID int(11) NOT NULL AUTO_INCREMENT,
			USUARIO varchar(45) DEFAULT NULL,
			PASSWORD varchar(45) DEFAULT NULL,
			ESTADO varchar(45) DEFAULT NULL,
			PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE USUARIO_TOKEN (
			ID int(11) NOT NULL AUTO_INCREMENT,
			USUARIOID varchar(45) DEFAULT NULL,
			TOKEN varchar(45) DEFAULT NULL,
			ESTADO varchar(45) CHARACTER SET armscii8 DEFAULT NULL,
			FECHA datetime DEFAULT NULL,
			PRIMARY KEY (ID)
)ENGINE=InnoDB;

INSERT INTO PRODUCTO (NAME) VALUES ('Hamburguesa simple');

INSERT INTO PRODUCTO (NAME) VALUES ('Hamburguesa con queso');

INSERT INTO PRODUCTO (NAME) VALUES ('Hamburguesa con queso');

INSERT INTO PRODUCTO (NAME) VALUES ('Hamburguesa de pollo');

INSERT INTO PRODUCTO (NAME) VALUES ('Hamburguesa vegana');

INSERT INTO PRODUCTO (NAME) VALUES ('Patatas fritas');

INSERT INTO PRODUCTO (NAME) VALUES ('Ensalada');

INSERT INTO PRODUCTO (NAME) VALUES ('Helado');

INSERT INTO PRODUCTO (NAME) VALUES ('Refresco de cola');

INSERT INTO PRODUCTO (NAME) VALUES ('Refresco de naranja');

INSERT INTO PRODUCTO (NAME) VALUES ('Agua');

INSERT INTO PRODUCTO (NAME) VALUES ('Cerveza');

INSERT INTO USUARIO (USUARIO, PASSWORD, ESTADO) VALUES
('user1@gmail.com', 'e10adc3949ba59abbe56e057f20f883e', 'Activo'),
('user2@gmail.com', 'e10adc3949ba59abbe56e057f20f883e', 'Activo');